## Add this file to your meteor package as `.travis.yml`

sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "npm install -g velocity-cli"
  - "npm install -g spacejam"
  - "curl -L https://raw.githubusercontent.com/dmitrijs-balcers/cah/master/meteor_install.sh | /bin/sh"
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
script:
  - "TEST_ENV=TEST spacejam test-packages --velocity --driver-package respondly:test-reporter"