## Add this file to your meteor package as `.travis.yml`

sudo: false
language: node_js
node_js:
  - "0.10.36"

before_install:
  - "curl -L https://raw.githubusercontent.com/dmitrijs-balcers/cah/master/meteor_install.sh | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - "npm install -g spacejam"
  - "npm install -g velocity-cli"

script:
  - "TEST_ENV=TEST spacejam test-packages --velocity --driver-package respondly:test-reporter"